name: test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: hng12-2-fastapi

    steps:
      - name: Debug Before Checkout
        run: |
          echo "Checking if repository directory exists before checkout..."
          ls -la /home/ubuntu/fastapi/ || echo "Directory does not exist"

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 1
          path: ~/fastapi/${{ github.event.repository.name }}

      - name: Debug After Checkout
        run: |
          echo "Checking if repository directory exists after checkout..."
          ls -la $GITHUB_WORKSPACE/fastapi-book-project || echo "Checkout failed"

      - name: Fix Runner Permissions
        run: |
          sudo chown -R $USER:$USER ~/fastapi/
          sudo chmod -R u+rwX ~/fastapi/

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest
