name: test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: hng12-2-fastapi

    steps:
      - name: Fix File Ownership & Clean Old Files
        run: |
          sudo rm -rf ~/fastapi/fastapi-book-project || true
          sudo chown -R $USER:$USER ~/fastapi
          sudo chmod -R u+rwX ~/fastapi

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 0

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest
